name: XTTS Voice Clone

on:
  workflow_dispatch:

jobs:
  clone-voice:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install TTS torch torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Download XTTS model release
        run: |
          curl -L -o xtts_v2.zip https://github.com/Armx-123/speech/releases/download/v1.0.0/xtts_v2.zip
          unzip xtts_v2.zip -d models/xtts_v2

      - name: Download voice sample from release
        run: |
          curl -L -o voice_sample.wav https://github.com/Armx-123/speech/releases/download/v1.0.0/voice_sample.wav

      - name: Run voice cloning script
        run: |
          python clone_voice.py
        env:
          TTS_AUTO_ACCEPT: 1

      - name: Upload generated audio
        uses: actions/upload-artifact@v4
        with:
          name: cloned-voice
          path: output/*.wav
