name: Generate TTS

on:
  workflow_dispatch: # run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install TTS
          sudo apt-get update
          sudo apt-get install -y espeak-ng

      - name: Run TTS script
        run: python scripts/tts.py

      - name: Upload MP3 outputs
        uses: actions/upload-artifact@v4
        with:
          name: tts-audio-files
          path: outputs/*.mp3
