name: Generate English Male TTS

on:
  workflow_dispatch: # manual trigger

jobs:
  tts-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y espeak-ng

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install TTS

      - name: Run TTS script
        run: python scripts/tts_male.py

      - name: Upload MP3 outputs
        uses: actions/upload-artifact@v4
        with:
          name: tts-male-outputs
          path: outputs/*.mp3
