name: Generate TTS

on:
  workflow_dispatch:

jobs:
  tts-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y espeak-ng libespeak-ng1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install TTS

      - name: Run TTS script
        run: python scripts/tts.py

      - name: Upload TTS outputs
        uses: actions/upload-artifact@v4
        with:
          name: tts-outputs
          path: tts_outputs/
