name: Run TTS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-tts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install TTS torch

      - name: Download TTS model from Release
        run: |
          mkdir -p models/xtts_v2
          curl -L -o xtts_v2.zip https://github.com/Armx-123/speech/releases/download/v1.0.0/xtts_v2.zip
          unzip xtts_v2.zip -d models/xtts_v2
          ls -R models/xtts_v2


      - name: Run clone_voice
        run: python clone_voice.py
