name: Run TTS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-tts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install TTS torch

      - name: Download TTS model
        run: |
          mkdir -p models/xtts_v2
          curl -L -o xtts_v2.zip https://huggingface.co/coqui/XTTS-v2/resolve/main/xtts_v2.zip
          unzip -o xtts_v2.zip -d models/xtts_v2
          ls -R models/xtts_v2

      - name: Run clone_voice
        run: python clone_voice.py
